// biome-ignore-all lint: generated by TanStack Router

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/root";
import { Route as workflowsRouteImport } from "./routes/workflows";
import { Route as settingsRouteImport } from "./routes/settings";
import { Route as remindersRouteImport } from "./routes/reminders";
import { Route as pulseRouteImport } from "./routes/pulse";
import { Route as projectsRouteImport } from "./routes/projects";
import { Route as orgRouteImport } from "./routes/org";
import { Route as agentsRouteImport } from "./routes/agents";
import { Route as indexRouteImport } from "./routes/index";
import { Route as workflowsDotworkflowIdRouteImport } from "./routes/workflows.$workflowId";
import { Route as projectsDotprojectIdRouteImport } from "./routes/projects.$projectId";
import { Route as orgDotworkRouteImport } from "./routes/org.work";
import { Route as orgDotmyWorkRouteImport } from "./routes/org.my-work";
import { Route as messagesDotnewRouteImport } from "./routes/messages.new";
import { Route as channelsDotchannelIdRouteImport } from "./routes/channels.$channelId";
import { Route as orgDotworkDotitemIdRouteImport } from "./routes/org.work.$itemId";
import { Route as orgDotdirectionDotslugRouteImport } from "./routes/org.direction.$slug";
import { Route as channelsDotchannelIdDotpostsDotpostIdRouteImport } from "./routes/channels.$channelId.posts.$postId";

const workflowsRoute = workflowsRouteImport.update({
  id: "/workflows",
  path: "/workflows",
  getParentRoute: () => rootRouteImport,
} as any);
const settingsRoute = settingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const remindersRoute = remindersRouteImport.update({
  id: "/reminders",
  path: "/reminders",
  getParentRoute: () => rootRouteImport,
} as any);
const pulseRoute = pulseRouteImport.update({
  id: "/pulse",
  path: "/pulse",
  getParentRoute: () => rootRouteImport,
} as any);
const projectsRoute = projectsRouteImport.update({
  id: "/projects",
  path: "/projects",
  getParentRoute: () => rootRouteImport,
} as any);
const orgRoute = orgRouteImport.update({
  id: "/org",
  path: "/org",
  getParentRoute: () => rootRouteImport,
} as any);
const agentsRoute = agentsRouteImport.update({
  id: "/agents",
  path: "/agents",
  getParentRoute: () => rootRouteImport,
} as any);
const indexRoute = indexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const workflowsDotworkflowIdRoute = workflowsDotworkflowIdRouteImport.update({
  id: "/workflows/$workflowId",
  path: "/workflows/$workflowId",
  getParentRoute: () => rootRouteImport,
} as any);
const projectsDotprojectIdRoute = projectsDotprojectIdRouteImport.update({
  id: "/projects/$projectId",
  path: "/projects/$projectId",
  getParentRoute: () => rootRouteImport,
} as any);
const orgDotworkRoute = orgDotworkRouteImport.update({
  id: "/org/work",
  path: "/org/work",
  getParentRoute: () => rootRouteImport,
} as any);
const orgDotmyWorkRoute = orgDotmyWorkRouteImport.update({
  id: "/org/my-work",
  path: "/org/my-work",
  getParentRoute: () => rootRouteImport,
} as any);
const messagesDotnewRoute = messagesDotnewRouteImport.update({
  id: "/messages/new",
  path: "/messages/new",
  getParentRoute: () => rootRouteImport,
} as any);
const channelsDotchannelIdRoute = channelsDotchannelIdRouteImport.update({
  id: "/channels/$channelId",
  path: "/channels/$channelId",
  getParentRoute: () => rootRouteImport,
} as any);
const orgDotworkDotitemIdRoute = orgDotworkDotitemIdRouteImport.update({
  id: "/org/work/$itemId",
  path: "/org/work/$itemId",
  getParentRoute: () => rootRouteImport,
} as any);
const orgDotdirectionDotslugRoute = orgDotdirectionDotslugRouteImport.update({
  id: "/org/direction/$slug",
  path: "/org/direction/$slug",
  getParentRoute: () => rootRouteImport,
} as any);
const channelsDotchannelIdDotpostsDotpostIdRoute =
  channelsDotchannelIdDotpostsDotpostIdRouteImport.update({
    id: "/channels/$channelId/posts/$postId",
    path: "/channels/$channelId/posts/$postId",
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof indexRoute;
  "/agents": typeof agentsRoute;
  "/org": typeof orgRoute;
  "/projects": typeof projectsRoute;
  "/pulse": typeof pulseRoute;
  "/reminders": typeof remindersRoute;
  "/settings": typeof settingsRoute;
  "/workflows": typeof workflowsRoute;
  "/channels/$channelId": typeof channelsDotchannelIdRoute;
  "/messages/new": typeof messagesDotnewRoute;
  "/org/my-work": typeof orgDotmyWorkRoute;
  "/org/work": typeof orgDotworkRoute;
  "/projects/$projectId": typeof projectsDotprojectIdRoute;
  "/workflows/$workflowId": typeof workflowsDotworkflowIdRoute;
  "/org/direction/$slug": typeof orgDotdirectionDotslugRoute;
  "/org/work/$itemId": typeof orgDotworkDotitemIdRoute;
  "/channels/$channelId/posts/$postId": typeof channelsDotchannelIdDotpostsDotpostIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof indexRoute;
  "/agents": typeof agentsRoute;
  "/org": typeof orgRoute;
  "/projects": typeof projectsRoute;
  "/pulse": typeof pulseRoute;
  "/reminders": typeof remindersRoute;
  "/settings": typeof settingsRoute;
  "/workflows": typeof workflowsRoute;
  "/channels/$channelId": typeof channelsDotchannelIdRoute;
  "/messages/new": typeof messagesDotnewRoute;
  "/org/my-work": typeof orgDotmyWorkRoute;
  "/org/work": typeof orgDotworkRoute;
  "/projects/$projectId": typeof projectsDotprojectIdRoute;
  "/workflows/$workflowId": typeof workflowsDotworkflowIdRoute;
  "/org/direction/$slug": typeof orgDotdirectionDotslugRoute;
  "/org/work/$itemId": typeof orgDotworkDotitemIdRoute;
  "/channels/$channelId/posts/$postId": typeof channelsDotchannelIdDotpostsDotpostIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof indexRoute;
  "/agents": typeof agentsRoute;
  "/org": typeof orgRoute;
  "/projects": typeof projectsRoute;
  "/pulse": typeof pulseRoute;
  "/reminders": typeof remindersRoute;
  "/settings": typeof settingsRoute;
  "/workflows": typeof workflowsRoute;
  "/channels/$channelId": typeof channelsDotchannelIdRoute;
  "/messages/new": typeof messagesDotnewRoute;
  "/org/my-work": typeof orgDotmyWorkRoute;
  "/org/work": typeof orgDotworkRoute;
  "/projects/$projectId": typeof projectsDotprojectIdRoute;
  "/workflows/$workflowId": typeof workflowsDotworkflowIdRoute;
  "/org/direction/$slug": typeof orgDotdirectionDotslugRoute;
  "/org/work/$itemId": typeof orgDotworkDotitemIdRoute;
  "/channels/$channelId/posts/$postId": typeof channelsDotchannelIdDotpostsDotpostIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/agents"
    | "/org"
    | "/projects"
    | "/pulse"
    | "/reminders"
    | "/settings"
    | "/workflows"
    | "/channels/$channelId"
    | "/messages/new"
    | "/org/my-work"
    | "/org/work"
    | "/projects/$projectId"
    | "/workflows/$workflowId"
    | "/org/direction/$slug"
    | "/org/work/$itemId"
    | "/channels/$channelId/posts/$postId";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/agents"
    | "/org"
    | "/projects"
    | "/pulse"
    | "/reminders"
    | "/settings"
    | "/workflows"
    | "/channels/$channelId"
    | "/messages/new"
    | "/org/my-work"
    | "/org/work"
    | "/projects/$projectId"
    | "/workflows/$workflowId"
    | "/org/direction/$slug"
    | "/org/work/$itemId"
    | "/channels/$channelId/posts/$postId";
  id:
    | "__root__"
    | "/"
    | "/agents"
    | "/org"
    | "/projects"
    | "/pulse"
    | "/reminders"
    | "/settings"
    | "/workflows"
    | "/channels/$channelId"
    | "/messages/new"
    | "/org/my-work"
    | "/org/work"
    | "/projects/$projectId"
    | "/workflows/$workflowId"
    | "/org/direction/$slug"
    | "/org/work/$itemId"
    | "/channels/$channelId/posts/$postId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute;
  agentsRoute: typeof agentsRoute;
  orgRoute: typeof orgRoute;
  projectsRoute: typeof projectsRoute;
  pulseRoute: typeof pulseRoute;
  remindersRoute: typeof remindersRoute;
  settingsRoute: typeof settingsRoute;
  workflowsRoute: typeof workflowsRoute;
  channelsDotchannelIdRoute: typeof channelsDotchannelIdRoute;
  messagesDotnewRoute: typeof messagesDotnewRoute;
  orgDotmyWorkRoute: typeof orgDotmyWorkRoute;
  orgDotworkRoute: typeof orgDotworkRoute;
  projectsDotprojectIdRoute: typeof projectsDotprojectIdRoute;
  workflowsDotworkflowIdRoute: typeof workflowsDotworkflowIdRoute;
  orgDotdirectionDotslugRoute: typeof orgDotdirectionDotslugRoute;
  orgDotworkDotitemIdRoute: typeof orgDotworkDotitemIdRoute;
  channelsDotchannelIdDotpostsDotpostIdRoute: typeof channelsDotchannelIdDotpostsDotpostIdRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/workflows": {
      id: "/workflows";
      path: "/workflows";
      fullPath: "/workflows";
      preLoaderRoute: typeof workflowsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof settingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/reminders": {
      id: "/reminders";
      path: "/reminders";
      fullPath: "/reminders";
      preLoaderRoute: typeof remindersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/pulse": {
      id: "/pulse";
      path: "/pulse";
      fullPath: "/pulse";
      preLoaderRoute: typeof pulseRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/projects": {
      id: "/projects";
      path: "/projects";
      fullPath: "/projects";
      preLoaderRoute: typeof projectsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/org": {
      id: "/org";
      path: "/org";
      fullPath: "/org";
      preLoaderRoute: typeof orgRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/agents": {
      id: "/agents";
      path: "/agents";
      fullPath: "/agents";
      preLoaderRoute: typeof agentsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof indexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/workflows/$workflowId": {
      id: "/workflows/$workflowId";
      path: "/workflows/$workflowId";
      fullPath: "/workflows/$workflowId";
      preLoaderRoute: typeof workflowsDotworkflowIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/projects/$projectId": {
      id: "/projects/$projectId";
      path: "/projects/$projectId";
      fullPath: "/projects/$projectId";
      preLoaderRoute: typeof projectsDotprojectIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/org/work": {
      id: "/org/work";
      path: "/org/work";
      fullPath: "/org/work";
      preLoaderRoute: typeof orgDotworkRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/org/my-work": {
      id: "/org/my-work";
      path: "/org/my-work";
      fullPath: "/org/my-work";
      preLoaderRoute: typeof orgDotmyWorkRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/messages/new": {
      id: "/messages/new";
      path: "/messages/new";
      fullPath: "/messages/new";
      preLoaderRoute: typeof messagesDotnewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/channels/$channelId": {
      id: "/channels/$channelId";
      path: "/channels/$channelId";
      fullPath: "/channels/$channelId";
      preLoaderRoute: typeof channelsDotchannelIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/org/work/$itemId": {
      id: "/org/work/$itemId";
      path: "/org/work/$itemId";
      fullPath: "/org/work/$itemId";
      preLoaderRoute: typeof orgDotworkDotitemIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/org/direction/$slug": {
      id: "/org/direction/$slug";
      path: "/org/direction/$slug";
      fullPath: "/org/direction/$slug";
      preLoaderRoute: typeof orgDotdirectionDotslugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/channels/$channelId/posts/$postId": {
      id: "/channels/$channelId/posts/$postId";
      path: "/channels/$channelId/posts/$postId";
      fullPath: "/channels/$channelId/posts/$postId";
      preLoaderRoute: typeof channelsDotchannelIdDotpostsDotpostIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  agentsRoute: agentsRoute,
  orgRoute: orgRoute,
  projectsRoute: projectsRoute,
  pulseRoute: pulseRoute,
  remindersRoute: remindersRoute,
  settingsRoute: settingsRoute,
  workflowsRoute: workflowsRoute,
  channelsDotchannelIdRoute: channelsDotchannelIdRoute,
  messagesDotnewRoute: messagesDotnewRoute,
  orgDotmyWorkRoute: orgDotmyWorkRoute,
  orgDotworkRoute: orgDotworkRoute,
  projectsDotprojectIdRoute: projectsDotprojectIdRoute,
  workflowsDotworkflowIdRoute: workflowsDotworkflowIdRoute,
  orgDotdirectionDotslugRoute: orgDotdirectionDotslugRoute,
  orgDotworkDotitemIdRoute: orgDotworkDotitemIdRoute,
  channelsDotchannelIdDotpostsDotpostIdRoute:
    channelsDotchannelIdDotpostsDotpostIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
